### ISSUE TITLE
No internet connection on Arch

### ISSUE THREAD

**Issue by benwaffle** [flathub/com.spotify.Client#1]

**Comment by TingPing** [comment]
Any more details than that? Maybe an SSL issue?

**Comment by benwaffle** [comment]
Here's the output:
```
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0618/234025.541817:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[0618/234026.012116:ERROR:interface_registry.cc(203)] Failed to locate a binder for interface: blink::mojom::SensitiveInputVisibilityService requested by: content_renderer exposed by: content_browser via InterfaceProviderSpec "navigation:frame".
[0618/234026.645288:ERROR:KeyboardEventManager.cpp(427)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()
```

**Comment by TingPing** [comment]
I get the same output but everything works fine.

**Comment by benwaffle** [comment]
How would I debug?

**Comment by benwaffle** [comment]
works now

**Comment by benwaffle** [comment]
It fixed itself, unfortunately

**Comment by smichel17** [comment]
I had a similar problem on Fedora, where I could not log in (auth error 1); the terminal output complained about libcurl being missing; and uninstall/reinstalling did not fix the problem.

It turns out that uninstalling did *not* remove all traces of spotify from my system — in fact there was quite a bit of stuff left. I was able to get spotify working again by manually removing everything spotify related that I could find, rebooting, and installing it fresh again.

Commands I used to try and uninstall the normal way. I am not sure if `--delete-data` works the way I think it does; I was just trying options. It uninstalled successfully but also printed an error message; maybe try with sudo?
```sh
flatpak uninstall --delete-data com.spotify.Client
flatpak uninstall --unused
sudo flatpak repair
```
I also killed a running process, not sure if that was needed
```sh
ps aux | grep spotify # list proc
kill -9 #{process id here}
```
Here's a list of files and folders I removed. Most of them need `sudo` — be careful with your `rm -rf`s! One strategy is — type the command first using just `rm`, then once you've got the path right, jump back to the beginning (with the home key) and add the `sudo` prefix and `-rf` flags.
```
/var/lib/flatpak/app/com.spotify.Client/
/var/lib/flatpak/exports/bin/com.spotify.Client
/var/lib/flatpak/exports/share/icons/hicolor/scalable/apps/com.spotify.Client.svg
/var/lib/flatpak/exports/share/icons/hicolor/scalable/apps/com.spotify.Client.svg
/var/lib/flatpak/exports/share/applications/com.spotify.Client.desktop
/var/lib/flatpak/repo/refs/heads/deploy/app/com.spotify.Client/
/var/lib/flatpak/repo/refs/remotes/flathub/app/com.spotify.Client/x
/usr/lib/firewalld/services/spotify-sync.xml # Don't know if this one was from flatpak.
$HOME/.cache/gnome-software/odrs/com.spotify.Client.desktop.json
$HOME/.cache/gnome-software/odrs/com.spotify.Client.json
$HOME/.cache/gnome-software/cssresource/dfbb0dfc3dd596f20f329a8d0e3fa1dc4ab8af97-spotify-logo.svg
$HOME/.var/app/com.spotify.Client/
/var/tmp/flatpak-cache-EGQUZ0/
```
The last one was difficult to remove, even `sudo rm -rf` didn't work — I had to manually `cd` down into the folder and delete files, then `sudo rmdir` the folder. It's possible that the files were locked by the process that I killed above, and killing it allowed me to remove the files. The steps I'm listing here are not in order; I wasn't intending to write a how-to; I'm only doing it now because I couldn't find this info anywhere else.
