### ISSUE TITLE
Installtion issue Deepin

### ISSUE THREAD

**Issue by paulorenatoxs** [flathub/com.spotify.Client#17]
I am trying to install Spotify in Deepin 15.5 and only managed to install as user not as system. When I tried intall as system a got this error:

$ flatpak install flathub com.spotify.Client
Instalando: com.spotify.Client/x86_64/stable de flathub
[                    ] Downloading metadata: 0/(estimating) 90,7 MB (347,6 kB/s) 
erro: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

**Comment by Barthalion** [comment]
Can you try again? Should be fixed by recent commits.

**Comment by joergister** [comment]
it is unfortunatly not fixed in this case. Not sure if it is because of the distro (Deepin 15.5) or the version of flatpak (0.9.7). I know its not the latest version. But as Deepin is based on Debian, they ship this version in their repositories. 
About 2 weeks ago, I was able to install the spotify flatpak succesfully on KDE-Neon with flatpak installed from the flatpak PPA (always the latest version, in my case version 0.10.2.1). 

But anyway, when I try to install spotify as a flatpak by tiping 

`flatpak install flathub com.spotify.Client`

 I get

```
Installieren: com.spotify.Client/x86_64/stable von flathub
[####################] Downloading: 102,0 MB/102,0 MB (128,3 kB/s) 
Fehler: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
```

So to me it seems possible, that your package is not responsible for the described missbehavior, but the version of Flatpak Deepin ships is their repositories.
