### ISSUE TITLE
Multiple fractional scale related regressions on Gnome 47 wayland

### ISSUE THREAD

**Issue by nicolas-yangli** [flathub/com.spotify.Client#306]
I updated to version 1.2.45.454.gc16ec9f6 today and encountered multiple fractional scale related issues, making it unusable:

1. mouse cursor offset
2. cannot adjust the size of the window, as cursor offset makes me unable to select the window border
3. the right part and bottom part of the window are cropped.

![截图 2024-10-01 23-30-56](https://github.com/user-attachments/assets/d6585f1d-ecc0-4ba5-b5b7-03ec76f5c6f3)

I uses Gnome 47 wayland with xwayland fractional scale feature enabled:

```
~ ❯ gsettings get org.gnome.mutter experimental-features
['scale-monitor-framebuffer', 'xwayland-native-scaling']
```

The previous version works well on Gnome 47.

**Comment by TingPing** [comment]
@ZVNexus

**Comment by ZVNexus** [comment]
@nicolas-yangli Looks like you're running in native Wayland mode, you can go back to XWayland and rely on GNOME 47's ability to let the application scale itself with:
`flatpak override --user --nosocket=wayland com.spotify.Client`

Not sure how this can be a regression though, since the feature to enable native Wayland was not introduced until just yesterday.

Everything is fine here on Ubuntu 24.10 w/GNOME 47 `['scale-monitor-framebuffer', 'xwayland-native-scaling']`:

![Screenshot From 2024-10-01 14-03-04](https://github.com/user-attachments/assets/08f1ccf2-d26e-4462-9806-af532adc6562)

@TingPing For native Wayland looks like https://github.com/flathub/com.spotify.Client/pull/299#discussion_r1779814508 is still needed for GNOME. I was testing that particular bit on KDE 6 and it works fine there without it, will open a PR to add it.

Strange though that it's needed on GNOME and not KDE though? Especially per Erick's comment.

**Comment by ZVNexus** [comment]
Also about the window being cropped, it looks like specifically the 'xwayland-native-scaling' experimental mutter feature is causing this to happen. I unset it and looks fine now (besides fallback client side decorations):
![image](https://github.com/user-attachments/assets/e5d6c159-b1ee-4baa-a203-b6b769d6815e)

**Comment by nicolas-yangli** [comment]
> @nicolas-yangli Looks like you're running in native Wayland mode, you can go back to XWayland and rely on GNOME 47's ability to let the application scale itself with: `flatpak override --user --nosocket=wayland com.spotify.Client`
> 
> Not sure how this can be a regression though, since the feature to enable native Wayland was not introduced until just yesterday.
> 
> Everything is fine here on Ubuntu 24.10 w/GNOME 47 `['scale-monitor-framebuffer', 'xwayland-native-scaling']`:
> 

Oh, I  did not found that the new version run in native wayland. You are right. It works well after I go back to XWayland.

**Comment by ZVNexus** [comment]
> Also about the window being cropped when running Spotify as a native Wayland app, it looks like specifically the 'xwayland-native-scaling' experimental mutter feature is causing this to happen.

Looks like this is only the case if you don't log out and log back in after setting the mutter flags, all good now.

```
nexus@prism:~$ gsettings get org.gnome.mutter experimental-features
['scale-monitor-framebuffer', 'xwayland-native-scaling']
```
![image](https://github.com/user-attachments/assets/40a57a8b-9682-4377-a2ac-663de5427d86)

**Comment by nicolas-yangli** [comment]
So, you don't have scale and cropping problems with native wayland on Gnome 47 with Ubuntu 24.10. I am using Arch Linux, and when using native wayland,  I have these problems,  even though I log out and log back in after setting the mutter flags.

This makes the problem complicated. I don't have any idea about how to diagnose now. Do you have any suggestion?

**Comment by ZVNexus** [comment]
> So, you don't have scale and cropping problems with native wayland on Gnome 47 with Ubuntu 24.10. I am using Arch Linux, and when using native wayland, I have these problems, even though I log out and log back in after setting the mutter flags.
> 
> This makes the problem complicated. I don't have any idea about how to diagnose now. Do you have any suggestion?

I'll take a look on Arch specifically in a bit
